server:
  port: 8080
  servlet:
    context-path: /redis-sidecar-spring
    
spring:
  application:
    name: redis-sidecar-spring

  config:
    import: 
    - application-redis.yml
    
logging:
  level:
    root: info                                # all logging
    '[com.htdp1.redissidecarspring]': debug   # Application logging
